baseURL = "https://galaiko.rocks"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Nikita Galaiko"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10

[author]
  name = "Nikita Galaiko"

[params]
  description = "Nikita Galaiko"
  dark      = "auto"
  highlight = false
