baseURL = "https://galaiko.rocks"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Nikita Galaiko"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10

[build]
  writeStats = true

[author]
  name = "Nikita Galaiko"
  email = "nikita@galaiko.rocks"
  avatar = "/images/nikita.jpeg"
