baseURL = "https://galaiko.rocks"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Nikita Galaiko"
theme = "etch"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10

[author]
  name = "Nikita Galaiko"

[params]
  description = "Nikita Galaiko"
  dark      = "auto"
  highlight = false

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    name = "RSS"
    url = "/posts/index.xml"
    weight = 30
