app = "galaiko-rocks"
primary_region = "arn"

[mounts]
  source = "logs"
  destination = "/var/log"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  min_machines_running = 1

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 7890
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 7890

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
