[package]
name = "serve"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[build-dependencies]
lib = { path = "../lib" }
maud = "0.25.0"
rust-embed = { version = "8.1.0", features = ["include-exclude","mime-guess"] }

[dependencies]
lib = { path = "../lib" }
async-std = { version = "1.12.0", features = ["default", "attributes"] }
femme = "2.2.1"
rust-embed = { version = "8.1.0", features = ["include-exclude","mime-guess"] }
tide = { version = "0.16.0", features = ["default"] }
urlencoding = "2.1.3"
clap = { version = "4.4.11", features = ["derive"] }
