name: Create comment
on:
  workflow_dispatch:
    inputs:
      author_name:
        type: string
        required: true
        description: 'Author name'
      body:
        required: true
        type: string
        description: 'Comment body'
      pathname:
        required: true
        type: string
        description: 'Path of the page commenting on'

jobs:
  create_comment:
    runs-on: ubuntu-latest
    name: Create comment
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Create comment
        run: |
          export DIRNAME="./src/lib/comments${{ inputs.pathname }}"
          export ID=$(ls "$DIRNAME" | wc -l)
          export FILENAME="$DIRNAME/$ID.md"
          mkdir -p "${DIRNAME}"

          cat << EOF > "${FILENAME}"
          ---
          author_name: "${{ inputs.author_name }}"
          timestamp: $(date '+%s')
          ---

          ${{ inputs.body}} 
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'comments: new comment from ${{ inputs.author_name }}'
          title: 'New comment from ${{ inputs.author_name }}'
          body: ''
          reviewers: 'ngalaiko'
          delete-branch: true
          branch-suffix: 'timestamp'
