name: Create comment
on:
  workflow_dispatch:
    inputs:
      author_name:
        type: string
        required: true
        description: 'Author name'
      body:
        required: true
        type: string
        description: 'Comment body'
      pathname:
        required: true
        type: string
        description: 'Path of the page commenting on'

jobs:
  create_comment:
    runs-on: ubuntu-latest
    name: Create comment
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Create comment
        run: |
          export TIMESTAMP="$(date '+%s')"
          export FILENAME="./src/lib/comments/${TIMESTAMP}.md"
          mkdir -p "$(dirname $FILENAME)"
          echo '---'                                       > "${FILENAME}"
          echo 'pathname: "${{ inputs.pathname }}"'       >> "${FILENAME}"
          echo 'author-name: "${{ inputs.author_name }}"' >> "${FILENAME}"
          echo 'timestamp: "${TIMESTAMP}"'                >> "${FILENAME}"
          echo '---'                                      >> "${FILENAME}"
          echo ''                                         >> "${FILENAME}"
          echo '{{ $inputs.body }}'                       >> "${FILENAME}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'comments: new comment from ${{ inputs.author_name }}'
          title: 'New comment'
          body: ''
          reviewers: 'ngalaiko'
          delete-branch: true
          branch-suffix: 'timestamp'
