name: Daily job

on:
  workflow_dispatch: {}
  schedule:
    # every day at 3am
    - cron: "0 3 * * *"

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-suffix: "optional-suffix"

      - run: uv run ./scripts/update/letterboxd.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update movies

      - run: uv run ./scripts/update/discogs.py --token "${{ secrets.DISCOGS_API_KEY }}"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update records

      - name: Checkout ledger
        uses: actions/checkout@v3
        with:
          repository: ngalaiko/ledger
          token: ${{ secrets.GH_PAT }}
          path: "ledger"
          ref: "master"
      - run: sudo apt-get install ledger
      - run: uv run ./scripts/update/ledger.py --file "$GITHUB_WORKSPACE/ledger/main.ledger"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Restaurants and Cafes
