name: Daily job

on:
  workflow_dispatch: {}
  schedule:
    # every day at 3am
    - cron: "0 3 * * *"

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - run: cargo build -p update

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
      - run: python3 -m venv venv
      - run: source venv/bin/activate
      - run: python3 -m pip install -r requirements.txt

      - run: python3 ./scripts/update/letterboxd.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update movies

      - run: cargo run -p update discogs --token "${{ secrets.DISCOGS_API_KEY }}"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update records

      - name: Checkout ledger
        uses: actions/checkout@v3
        with:
          repository: ngalaiko/ledger
          token: ${{ secrets.GH_PAT }}
          path: "ledger"
          ref: "master"
      - name: Setup hledger
        uses: ngalaiko/setup-hledger@v1
      - run: cargo run -p update hledger --file "$GITHUB_WORKSPACE/ledger/main.ledger"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Restaurants and Cafes
