name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v1

      - name: Optimize images
        run: find ./content/media -type f -exec \
            mogrify -resize "1200>x" -quality 85 -format jpg {} \;

      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cname: galaiko.rocks
          args: --gc --minify --cleanDestinationDir
