name: Download webmentions

on:
  push:
  schedule:
    # every day at 3am
    - cron: '0 3 * * *'

jobs:
  download-webmentions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Yarn install
        run: |
          yarn install --frozen-lockfile

      - name: Yarn build
        run: |
          yarn build

      - name: Install wrangler
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          publish: false

      - name: Download webmentions
        run: |
          yarn webmentions:export \
            --file ./src/lib/data/webmentions.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Webmentions
