name: Update movies list

on:
  workflow_dispatch: {}
  schedule:
    # every day at 3am
    - cron: '0 3 * * *'

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Fetch records info
        run: |
          pnpm letterboxd:update \
            --output ./src/lib/movies/data.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update movies
