name: Update records list

on:
  schedule:
    # every day at 3am
    - cron: "0 3 * * *"

jobs:
  update-records:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Fetch records info
        run: |
          yarn generate:discogs \
            --api-token "${{ secrets.DISCOGS_API_KEY}}" \
            --output ./src/lib/data/records.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update records
