name: Update records list

on:
  schedule:
    # every day at 3am
    - cron: "0 3 * * *"

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Fetch records info
        run: |
          ./scripts/discogs/export.py ${{ secrets.DISCOGS_API_KEY}}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update records
