name: Update Restaurants and Cafes list

on:
  schedule:
    # every day at 3am
    - cron: '0 3 * * *'

jobs:
  update-restaurants-and-cafes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.5
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Checkout ledger
        uses: actions/checkout@v3
        with:
          repository: ngalaiko/ledger
          token: ${{ secrets.GH_PAT }}
          path: 'ledger'
          ref: 'master'

      - name: Setup hledger
        run: |
          TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)
          pushd "$TMP_DIR"
          curl -LO "https://github.com/simonmichael/hledger/releases/download/1.25/hledger-linux-x64.zip"
          unzip hledger-linux-x64.zip
          mkdir -p "$HOME/.local/bin"
          cp hledger-linux-x64 "$HOME/.local/bin/hledger"
          chmod +x "$HOME/.local/bin/hledger"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fetch list
        run: |
          pnpm ledger:restaurants-and-cafes \
            --file "$GITHUB_WORKSPACE/ledger/main.ledger" \
            --number 2 \
            --output ./src/lib/restaurants-and-cafes/data.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Restaurants and Cafes
