name: Updates
on:
  workflow_dispatch: {}
  schedule:
    # every 2 hours
    - cron: "0 */2 * * *"
jobs:
  letterboxd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/setup-uv@v5
      - run: uv run ./scripts/update/letterboxd.py
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-movies-${{ github.run_number }}
          title: "Update movies"
          body: "Automated update of movies data"
  discogs:
    runs-on: ubuntu-latest
    needs: [letterboxd]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/setup-uv@v5
      - run: uv run ./scripts/update/discogs.py --token "${{ secrets.DISCOGS_API_KEY }}"
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-records-${{ github.run_number }}
          title: "Update records"
          body: "Automated update of records data"
  blogroll:
    runs-on: ubuntu-latest
    if: always()
    needs: [discogs]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/setup-uv@v5
      - run: uv run ./scripts/update/blogroll.py
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-blogroll-${{ github.run_number }}
          title: "Update blogroll"
          body: "Automated update of blogroll data"
  ledger:
    runs-on: ubuntu-latest
    needs: [blogroll]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/setup-uv@v5
      - uses: actions/checkout@v4
        with:
          repository: ngalaiko/ledger
          token: ${{ secrets.GH_PAT }}
          path: "ledger"
          ref: "master"
      - run: sudo apt-get install ledger
      - run: uv run ./scripts/update/ledger.py --file "$GITHUB_WORKSPACE/ledger/main.ledger"
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-ledger-${{ github.run_number }}
          title: "Update Restaurants and Cafes"
          body: "Automated update of ledger data"
